### ISSUE TITLE
plz fix Miniget 404

### ISSUE THREAD

**Issue by MeTooIDK** [aoijs/aoi.js#212]
MinigetError: Status code: 404
    at ClientRequest.<anonymous> (/home/container/node_modules/miniget/dist/index.js:210:27)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10) {
  statusCode: 404
}

- Aoi.js version: 4.0.1
- Node.js version: 
- Operating system:

Screenshots (If any): Image or Link

**Comment by USERSATOSHI** [comment]
> MinigetError: Status code: 404
>     at ClientRequest.<anonymous> (/home/container/node_modules/miniget/dist/index.js:210:27)
>     at Object.onceWrapper (events.js:421:26)
>     at ClientRequest.emit (events.js:314:20)
>     at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
>     at TLSSocket.socketOnData (_http_client.js:474:22)
>     at TLSSocket.emit (events.js:314:20)
>     at addChunk (_stream_readable.js:297:12)
>     at readableAddChunk (_stream_readable.js:272:9)
>     at TLSSocket.Readable.push (_stream_readable.js:213:10) {
>   statusCode: 404
> }
> 
> 
> - Aoi.js version: 4.0.1
> - Node.js version: 
> - Operating system:
> 
> Screenshots (If any): Image or Link

read #support-1 pins @MeTooIDK

**Comment by MeTooIDK** [comment]
aoi.js discord?

**Comment by MeTooIDK** [comment]
But i got banned on their discord server

**Comment by Leref** [comment]
This has been fixed in latest commits.
An update will be released later on.
You may also update `ytdl-core` to fix the Error.
