### ISSUE TITLE
$attachment problem

### ISSUE THREAD

**Issue by Andrea055** [aoijs/aoi.js#322]
## Type
- [*] Functions: \$attachment
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
Your Code Here
const aoijs = require("aoi.js")

const bot = new aoijs.Bot({
token: "TOKEN", //Discord Bot Token
prefix: "?", //Discord Bot Prefix
intents: ["GUILDS", "GUILD_MESSAGES"] //Discord Intents
})

//Events
bot.onMessage()

//Command Example
bot.command({
name: "ping",
code: `Pong! $pingms`
})
bot.command({
  name: "dog",
  code: `$attachment[https://cdn.discordapp.com/attachments/773357374328012840/780585674541105152/20201116_133035.jpg] Take a pic of Kuba's dog!`
});

//Ready Event
bot.readyCommand({
    channel: "",
    code: `$log[Ready on $userTag[$clientID]]`
})

```

More:
- Aoi.js version: 5.0.1
- Node.js version: 16.13
- Operating system: Debian 11

Screenshots (If any): Enabled Status
Ready on NodeJSTest#8390
Initialized on aoi.js || v5.0.2
Our Official Discord Server: https://aoi.js.org/invite
TypeError: Cannot read properties of undefined (reading 'addBrackets')
    at Function.module.exports [as code] (/home/andrelaptop/Scrivania/DiscordBotJS/node_modules/aoi.js/package/functions/Funcs/calling/attachment.js:8:73)
    at Interpreter (/home/andrelaptop/Scrivania/DiscordBotJS/node_modules/aoi.js/package/interpreter.js:70:108)
    at module.exports (/home/andrelaptop/Scrivania/DiscordBotJS/node_modules/aoi.js/package/Handler/guildMessages/commands.js:74:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (/home/andrelaptop/Scrivania/DiscordBotJS/node_modules/aoi.js/package/classes/Bot.js:22:13)

**Comment by USERSATOSHI** [comment]
you need to give the attachment a name

**Comment by NeoAIChan** [comment]
How does data part works though?

**Comment by USERSATOSHI** [comment]
> How does data part works though?

attachment doesnt have any data part tho

**Comment by USERSATOSHI** [comment]
> > you need to give the attachment a name
> 
> Where? I copy the command as write as docs

$attachment[url;name]

**Comment by Leref** [comment]
No response.
