### ISSUE TITLE
$channelExists does not see threads..

### ISSUE THREAD

**Issue by Silmarill-D** [aoijs/aoi.js#396]
## Type
- [ ] Functions: \$channelExists
- [ ] Callbacks:  -
- [ ] Handlers: Command Handler
- [ ] Others: -

Example code used:
```
$channelExists[threadID]
```

The unexpected error message or issue: 
```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /home/container/node_modules/aoi.js/src/functions/Funcs/util/channelExists.js:9:56
    at Map.find (/home/container/node_modules/aoi.js/node_modules/@discordjs/collection/dist/index.js:122:11)
    at Function.module.exports [as code] (/home/container/node_modules/aoi.js/src/functions/Funcs/util/channelExists.js:9:39)
    at Object.Interpreter [as interpreter] (/home/container/node_modules/aoi.js/src/interpreter.js:319:23)
    at Function.module.exports [as code] (/home/container/node_modules/aoi.js/src/functions/Funcs/misc/eval.js:7:26)
    at Interpreter (/home/container/node_modules/aoi.js/src/interpreter.js:319:23)
    at runMicrotasks (<anonymous>)

//Such an error in the console stops code execution rather than just returning an empty value.
```

Information:
- aoi.js version: 5.5.5
- node.js version: 17.9.1
- Operating system: Linux

Screenshots (If any): Described in detail above

**Comment by USERSATOSHI** [comment]
ok I saw that line in src ,
and the error seems to caused by broken cache
aka
ur cache has a channel with incomplete data
a restart should fix this

**Comment by Silmarill-D** [comment]
> ok I saw that line in src , and the error seems to caused by broken cache aka ur cache has a channel with incomplete data a restart should fix this

Thanks, rebooting helped!
