### ISSUE TITLE
Bug: Buttons Not working anymore after transferring database

### ISSUE THREAD

**Issue by acqualesce** [aoijs/aoi.js#427]
### Bug Type

Function

### Bugged function

```js
$interactionUpdate[;{newEmbed:{title:$userTag - CARD PACK}{description:Card has been claimed.

1 random card (**★★★★ PROBABILITY INCREASED!**):
\`$getGlobalUserVar[DROP4]\` ** $getGlobalUserVar[$getGlobalUserVar[DROP4]_RARE]** **$getGlobalUserVar[$getGlobalUserVar[DROP4]_GROUP]** $getGlobalUserVar[$getGlobalUserVar[DROP4]_NAME] ($getGlobalUserVar[$getGlobalUserVar[DROP4]_THEME])}
{image:$getGlobalUserVar[$getGlobalUserVar[DROP4]_IMAGE]}{color:$getGlobalUserVar[COLOR]}};
{actionRow:{button:OPEN CARD:1:dropresult_$authorID:true:}}
]
```

### Version of aoi.js

v5.5.5 (Default)

### Version of Node.js

v18.6.0+ (Latest)

### Excepted Output

The code actually works when I use the default database, but after transferring to mongodb/aoimongo the error occurs. I think theres nothing wrong in the codes since it works with the old database but after transferring $interactionUpdate and $interactionReply doesnt work already

**This is the error**
![mongodb](https://user-images.githubusercontent.com/71684328/200753852-03341a1c-6730-4cff-8b4b-3de58a00c3ce.png)

**This is what the output should look like**
![before transferring to mongodb (default database)](https://user-images.githubusercontent.com/71684328/200754027-75bc6919-22d4-4017-98e0-a467985523f1.png)

### Relevant log output

```shell
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/home/runner/test-1/node_modules/aoi.js/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/test-1/node_modules/aoi.js/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async ButtonInteraction.reply (/home/runner/test-1/node_modules/aoi.js/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:103:5)
    at async Function.module.exports [as code] (/home/runner/test-1/node_modules/aoi.js/src/functions/Funcs/events/interactionReply.js:12:5)
    at async Interpreter (/home/runner/test-1/node_modules/aoi.js/src/interpreter.js:317:28)
    at async module.exports (/home/runner/test-1/node_modules/aoi.js/src/handler/nonIntents/interaction.js:63:9) {
  method: 'post',
  path: '/interactions/1039786402419847208/aW50ZXJhY3Rpb246MTAzOTc4NjQwMjQxOTg0NzIwODphRFM1dXJycmRIYUszREpmV1Joa3ltZzlGMmV4RnF2SlV0U1hPMTNiV0NyQmIzSmc5djlMNkhlVzRleFhPeGtWZ3NqZzlFbXRqMjZTbVhqb3dIczYybW1IMW9NQ0xqWnFhUDYwMjJZRVhxMXlQY09EN1VRUDc1VWpLYk1Sd2JMVw/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
Can you send full code so that we can check which part is clashing
cause that error means that something already replied to your button's interaction before $interactionUpdate got its chance

**Comment by acqualesce** [comment]
this is the code for the addbutton part

```
module.exports = ({
  name: "use",
  aliases: ["u"],
    $if: "v4",

  code: `
  $if[$message[1]==]
Please Mention a CardPack.

$elseIf[$message[1]==CARDPACK4]  

$setGlobalUserVar[CARDPACK4;$sub[$getGlobalUserVar[CARDPACK4];1]]
 
 $title[$userTag - CARD PACK]
$description[$customEmoji[cardbox4;1034338967191040060] Click on the button to claim:

1 random card (**★★★★ PROBABILITY INCREASED!**)]
$addButton[1;OPEN CARD;1;dropresult2_$authorID;no]
 $setGlobalUserVar[DROP4;$randomText[SCPS4;JSHS4;WNWS4;VRNS4;DKMS4;SKNS4;JUNS4;WZIS4;HSHS4;MGYS4]

$color[$getGlobalUserVar[COLOR]]
$onlyIf[$getGlobalUserVar[CARDPACK4]>=1;You do not have enough **Card Packs** to use this command.]
$endelseIf
$elseIf[$message[1]!=CARDPACK1]
Please Mention a **VALID** Card Pack
$endelseIf
$elseIf[$message[1]!=CARDPACK4]
Please Mention a **VALID** Card Pack
$endelseIf
$elseIf[$message[1]!=CARDPACK5]
Please Mention a **VALID** Card Pack
$endelseIf
$endIf
  
  `


})
```
 
this is the code for the interactionUpdate part.

```
module.exports = {
type: 'interaction',
prototype: "button",
code: `

 $setVar[$getGlobalUserVar[DROP4];$sum[$getGlobalUserVar[$getGlobalUserVar[DROP4]];1
$setServerVar[$getGlobalUserVar[DROP4];$sum[$getServerVar[$getGlobalUserVar[DROP4]];1

$setGlobalUserVar[$getGlobalUserVar[DROP4];$sum[$getGlobalUserVar[$getGlobalUserVar[DROP4]];1]]
  $interactionUpdate[;{newEmbed:{title:$userTag - CARD PACK}{description:Card has been claimed.

1 random card (**★★★★ PROBABILITY INCREASED!**):
\`$getGlobalUserVar[DROP4]\` ** $getGlobalUserVar[$getGlobalUserVar[DROP4]_RARE]** **$getGlobalUserVar[$getGlobalUserVar[DROP4]_GROUP]** $getGlobalUserVar[$getGlobalUserVar[DROP4]_NAME] ($getGlobalUserVar[$getGlobalUserVar[DROP4]_THEME])}
{image:$getGlobalUserVar[$getGlobalUserVar[DROP4]_IMAGE]}{color:$getGlobalUserVar[COLOR]}};
{actionRow:{button:OPEN CARD:1:dropresult_$authorID:true:}}
]


$sendMessage[ $customEmoji[cardbox4;1034338967191040060] <@$authorID> got \`$getGlobalUserVar[DROP4]\` ** $getGlobalUserVar[$getGlobalUserVar[DROP4]_RARE]** **$getGlobalUserVar[$getGlobalUserVar[DROP4]_GROUP]** $getGlobalUserVar[$getGlobalUserVar[DROP4]_NAME] ($getGlobalUserVar[$getGlobalUserVar[DROP4]_THEME])]

  
  $onlyIf[$get[authorID]==$interactionData[author.id];{
"content" : "You aren't the author of this interaction.",
"ephemeral" : true,
"options" : { "interaction" : true }
}]

$onlyIf[$get[customId]==dropresult2;]

$let[authorID;$splitText[2]]
$let[customId;$splitText[1]] 
$textSplit[$interactionData[customId];_] 

`
}
```

Mind you the code works when using another database which isnt mongo, but when i use mongo as the db (aoi.mongo) then the error occurs, there are also some buttons that actually works but most of them are just bugged.

**Comment by USERSATOSHI** [comment]
> Mind you the code works when using another database which isnt mongo, but when i use mongo as the db (aoi.mongo) then the error occurs, there are also some buttons that actually works but most of them are just bugged.

@acqualesce oh then it must be because of the delay from mongo db

what you can do is change your button code to this

```php
// for $interactionReply code
$interactionFollowUp[msg with vars]
$interactionDefer[yes] // yes for emphemeral
```

```php
// for $interactionUpdate

$interactionEdit[msg with vars]
$interactioNDeferUpdate
```

i think this should be enough to fix it

**Comment by acqualesce** [comment]
Hi, I have tried the code you used and it sends another different errors regarding both functions. 

![image](https://user-images.githubusercontent.com/71684328/201014473-48ea4170-76e3-496e-857d-34c2830c36a5.png)

```
module.exports = {
type: 'interaction',
prototype: "button",
code: `
 $setVar[$getGlobalUserVar[DROPCLAIM];$sum[$getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]];1]
 $setGlobalUserVar[$getGlobalUserVar[DROPCLAIM];$sum[$getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]];1]]
 
$setServerVar[$getGlobalUserVar[DROPCLAIM];$sum[$getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]];1]
$interactionEdit[;{newEmbed:{title:$userTag - CARD PACK}{description:Card has been claimed.
 \`$getGlobalUserVar[DROPCLAIM]\` ** $getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_RARE]** 
 **$getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_GROUP]** $getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_NAME] ($getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_THEME])}
{image:$getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_IMAGE]}{color:$getGlobalUserVar[COLOR]}};
{actionRow:{button:REVEAL CARD:1:freecard_$authorID:true:}}
]
$sendMessage[$customEmoji[card;1034338967191040060] <@$authorID> got \`$getGlobalUserVar[DROPCLAIM]\` ** $getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_RARE]** **$getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_GROUP]** $getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_NAME] ($getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_THEME])]



$interactioNDeferUpdate


 
  
  $onlyIf[$get[authorID]==$interactionData[author.id];{
"content" : "You aren't the author of this interaction.",
"ephemeral" : true,
"options" : { "interaction" : true }
}]

$onlyIf[$get[customId]==freecard;]

$let[authorID;$splitText[2]]
$let[customId;$splitText[1]] 
$textSplit[$interactionData[customId];_] 
`
}
```
for reference, here is how i did it with the function.

**EDIT** I have tried transferring these functions everywhere in the code but still to no avail.

**Comment by USERSATOSHI** [comment]
why are u getting interactionDefer error and interactionDeferUpdate error in same msg

also where is the $interationEdit/FollowUp

**Comment by acqualesce** [comment]
> why are u getting interactionDefer error and interactionDeferUpdate error in same msg
> 
> also where is the $interationEdit/FollowUp

as for the both errors, i do not know why but for the interactionEdit heres the code.
```
`$interactionEdit[;{newEmbed:{title:$userTag - CARD PACK}{description:Card has been claimed.
 \`$getGlobalUserVar[DROPCLAIM]\` ** $getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_RARE]** 
 **$getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_GROUP]** $getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_NAME] ($getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_THEME])}
{image:$getGlobalUserVar[$getGlobalUserVar[DROPCLAIM]_IMAGE]}{color:$getGlobalUserVar[COLOR]}};
{actionRow:{button:REVEAL CARD:1:freecard_$authorID:true:}}
]`
```

**Comment by USERSATOSHI** [comment]
no activity
