### ISSUE TITLE
Bug: Bug when requesting icon from a specific guild using guild id

### ISSUE THREAD

**Issue by AbnerCae** [aoijs/aoi.js#484]
### Bug Type

Function

### Bugged Function

```js
module.exports = {
 name: 'servericon',
 code: `
 $guildIcon[$get[server]]
 $let[server;$if[$guildExists[$message[1]]==true;$message[1];$guildID]]
`
}
```

### Version of aoi.js

v6.5.0

### Version of Node.js

v18.17.1 (LTS)

### Excepted Output

The initial idea is that I could send an ID from a server to show an icon server that the bot is present, but, that is not the case.
When sending a test using "!servericon <id>" isn't working, and it presents an error in the logs. But sending just "!severicon", it worked.

### Relevant log output

```shell
Error [FileNotFound]: File could not be found: /home/runner/Layla-Canary
    at DataResolver.resolveFile (/home/runner/Layla-Canary/node_modules/discord.js/src/util/DataResolver.js:132:34)
    at async MessagePayload.resolveFile (/home/runner/Layla-Canary/node_modules/discord.js/src/structures/MessagePayload.js:258:35)
    at async Promise.all (index 0)
    at async MessagePayload.resolveFiles (/home/runner/Layla-Canary/node_modules/discord.js/src/structures/MessagePayload.js:223:18)
    at async TextChannel.send (/home/runner/Layla-Canary/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:161:29) {
  code: 'FileNotFound'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
cant reproduce @Leref

**Comment by Leref** [comment]
Unable to as well, please update to latest version, if issue occurs, reopen pull request.
