### ISSUE TITLE
Bug: TypeError (timeout.js)

### ISSUE THREAD

**Issue by xyloblonk** [aoijs/aoi.js#488]
### Bug Type

Function

### Bugged Function

```js
index.js

No related function
```

### Version of aoi.js

v6.5.0

### Version of Node.js

v18.17.1 (LTS)

### Relevant log output

```shell
node:events:492
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read properties of undefined (reading 'all')
    at module.exports (/home/container/node_modules/aoi.js/src/handler/Custom/timeout.js:6:37)
    at module.exports (/home/container/node_modules/aoi.js/src/handler/AoiStart.js:16:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (/home/container/node_modules/aoi.js/src/classes/AoiBase.js:109:13)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:395:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
Node.js v18.17.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ddodogames** [comment]
What's the index.js? Also, doesn't look like a Bug.

**Comment by Leref** [comment]
Appears to be possibly setup of database may not be implemented, I will soon begin making all database related features requiring setup.

**Comment by Leref** [comment]
Fixed in https://github.com/AkaruiDevelopment/aoi.js/commit/3da030ebe2fbf036eeb780fd80633a30d0da6567
