### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by UBizachoc** [aoijs/aoi.js#544]
### Bug Type

Function

### Bugged Function

```js
module.exports = [{
    name: "bonus",
    code: `
$title[1;Щоденна винагорода.]
$description[1;
**Ви отримуєте:** \`$random[100;1000]\` монет.
**Також:** \`$random[1;3]\` подарунків.]
$footer[1;Щоб перевірити баланс - $getGuildVar[prefix]bal]
$setUserVar[money;$sum[$getUserVar[money];$random[100;1000]]]
$setUserVar[podarki;$sum[$getUserVar[podarki];$random[1;3]]]
$color[1;$getGuildVar[color]]
$tempCooldown[24h;bonus;:clock4: | **Винагороду** можна отримати раз в один день.
Зачекайте: \`%time%\`.
]
`}]
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v21.4.0 (Current)

### Excepted Output

After using the command, the user should be given several gifts, and a certain number of coins, on this command cooldown, with which there are probably problems.

### Relevant log output

```shell
KeyValueError: [InvalidTable] :  Table __aoijs_vars__ not found!
    at KeyValue.get (/home/container/node_modules/aoi.db/dist/cjs/keyvalue/database.js:74:19)
    at Database.get (/home/container/node_modules/aoi.js/src/classes/Database.js:55:26)
    at module.exports [as code] (/home/container/node_modules/aoi.js/src/functions/database/advanceCooldown.js:10:38)
    at Interpreter (/home/container/node_modules/aoi.js/src/core/interpreter.js:335:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Please try to install the github version and see if this fixes your issue.

`npm install github:AkaruiDevelopment/aoi.js#v6`

**Comment by Faf4a** [comment]
Works as expected in the github version, closing due to inactivity.
