### ISSUE TITLE
Bug: Database bug

### ISSUE THREAD

**Issue by imzerott** [aoijs/aoi.js#547]
### Bug Type

Handler

### Bugged Function

```js
I'm not using any code, I just get this error out of nowhere
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v16.11.0 (Lowest)

### Relevant log output

```shell
[0m |
!Loaded 'eval' |default| [0m[0m
@| Loading in /home/node/comandos/testes/massremoverole.js[0m |
,Loaded 'massrole remove' |default| [0m[0m
Loaded 'd' |awaited| [0m[0m
Loaded 'c' |awaited| [0m[0m
:| Loading in /home/node/comandos/testes/massrole.js[0m |
)Loaded 'massrole add' |default| [0m[0m
Loaded 'a' |awaited| [0m[0m
Loaded 'b' |awaited| [0m[0m
6| Loading in /home/node/comandos/testes/test.js[0m |
!Loaded 'test' |default| [0m[0m
 Loaded 'sla' |awaited| [0m[0m
 Loaded 'sla' |default| [0m[0m
 Loaded 'aaa' |default| [0m[0m
$Loaded 'aaa' |interaction| [0m[0m
$Loaded 'bbb' |interaction| [0m[0m
Loaded 'a' |default| [0m[0m
"Loaded 'a' |interaction| [0m[0m
Loaded 'b' |default| [0m[0m
>| Loading in /home/node/comandos/utilidades/lembrete.js[0m |
%Loaded 'lembrete' |default| [0m[0m
%Loaded 'lembrete' |awaited| [0m[0m
 Loaded 'lbr' |awaited| [0m[0m
�╭───────────────────────────────────────────────╮
6│                    aoi.js                     │
6│              Installed on v6.6.1              │
6│ Discord Server: https://discord.gg/HMUfMXDQsV │
�╰───────────────────────────────────────────────╯
�╭──────────────────────────────────────────╮
1│             @akarui/aoi.db               │
1│ Successfully connected KeyValue database │
�╰──────────────────────────────────────────╯
C(node:1) DeprecationWarning: Using $if: old is deprecated. Use $if
K(Use `node --trace-deprecation ...` to show where the warning was created)
I/home/node/node_modules/aoi.js/src/handler/Custom/handleResidueData.js:4
+        const key = data.id.split("_")[0];
                            ^

ATypeError: Cannot read properties of undefined (reading 'split')
S    at /home/node/node_modules/aoi.js/src/handler/Custom/handleResidueData.js:4:29
c    at #findMany (/home/node/node_modules/@akarui/aoi.db/dist/cjs/KeyValue/src/newtable.js:598:21)
n    at async Table.findMany (/home/node/node_modules/@akarui/aoi.db/dist/cjs/KeyValue/src/newtable.js:581:21)
p    at async Table.deleteMany (/home/node/node_modules/@akarui/aoi.db/dist/cjs/KeyValue/src/newtable.js:639:29)
s    at async KeyValue.deleteMany (/home/node/node_modules/@akarui/aoi.db/dist/cjs/KeyValue/src/database.js:415:16)
`    at async Database.deleteMany (/home/node/node_modules/aoi.js/src/classes/Database.js:71:12)
l    at async handleResidueData (/home/node/node_modules/aoi.js/src/handler/Custom/handleResidueData.js:3:5)
_    at async Timeout._onTimeout (/home/node/node_modules/aoi.js/src/handler/AoiStart.js:35:13)

Node.js v18.19.0
```
Note: i'm using Discloud

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Have you tried updating to node.js >=20?

**Comment by Faf4a** [comment]
This is fixed in the latest version.
