### ISSUE TITLE
Bug: sharding dosent works normaly

### ISSUE THREAD

**Issue by scriptyyy13** [aoijs/aoi.js#553]
### Bug Type

Function

### Bugged Function

```js
$creationDate - not working when sharding enabled

and other sharding functions, $forEachGuild and $updatecommands doesnt works normaly when sharding enabled
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v21.4.0 (Current)

### Relevant log output

```shell
in $creationDate:
Error [ReferenceError]: id is not defined
    at eval (eval at _eval (/home/container/node_modules/discord.js/src/client/Client.js:502:12), <anonymous>:2:37)
    at eval (eval at _eval (/home/container/node_modules/discord.js/src/client/Client.js:502:12), <anonymous>:2:41)
    at Client._eval (/home/container/node_modules/discord.js/src/client/Client.js:502:12)
    at ShardClientUtil._handleMessage (/home/container/node_modules/discord.js/src/sharding/ShardClientUtil.js:207:82)
    at process.emit (node:events:530:35)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Foreachguild executes within one guild of the shard.

$updatecommands works for the current instance where you use the command. Not for all shards.

Don't know about creationDate

cc @Leref

**Comment by scriptyyy13** [comment]
and how to update commands on all shards at once? mb add an option to update commands without respawning shards, so that the music doesn't stop on all servers

**Comment by scriptyyy13** [comment]
$rolePerms dosent works with sharding with the same error $creationDate (there is an error in the first message)

**Comment by scriptyyy13** [comment]
will the $creationDate function be fixed when sharding is enabled?

**Comment by Faf4a** [comment]
@USERSATOSHI up to ya

**Comment by USERSATOSHI** [comment]
> will the $creationDate function be fixed when sharding is enabled?

does this also fail on latest version of aoi.js

**Comment by scriptyyy13** [comment]
> > will the $creationDate function be fixed when sharding is enabled?
> 
> does this also fail on latest version of aoi.js

yes

**Comment by Faf4a** [comment]
> $rolePerms dosent works with sharding with the same error 

Can't reproduce that, can reproduce $creationDate though

**Comment by USERSATOSHI** [comment]
creation date has been fixed we need more info and screenshots for rest of the functions

**Comment by Faf4a** [comment]
Closing due to inactivity.
