### ISSUE TITLE
Bug: $addMessageReactions is broken

### ISSUE THREAD

**Issue by LightslicerGP** [aoijs/aoi.js#665]
### Bug Type

Function

### Bugged Behavior

```js
bot.command({
  name: "test",
  code: `
    $addMessageReactions[$channelID;$messageID;✅;❎]
    `,
});
```

### Version of aoi.js

v6.8.x

### Version of Node.js

v22.5.1 (Current)

### Excepted Output

add reaction to a message, but the message never gets sent anyway so

### Relevant log output

TypeError: Cannot read properties of undefined (reading 'fnError')
    at module.exports [as code] (c:\Users\LightslicerGP\node_modules\aoi.js\src\functions\addMessageReactions.js:26:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Interpreter (c:\Users\LightslicerGP\node_modules\aoi.js\src\core\interpreter.js:309:28)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
no clue how nobody noticed this, fixing
